### ISSUE TITLE
[JS] tern_for_sublime popup keeps appearing

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/sublimious#25]

**Comment by senseisimple** [comment]
If Tern has been installed correctly, you will need to update your tern_for_submile user settings to point to the installation location; node/npm are properly configured on my system and are in path but the extension could not find it:

 {
    "tern_argument_hints": false,
    "tern_output_style": "tooltip",
    "tern_argument_completion": false,
   *\* "tern_command": ["node","~/.config/sublime-text-3/Packages/tern_for_sublime/node_modules/tern/bin/tern"]**
}

Sublimious should likely check for this dependency as part of the plugin install and/or since the tern for sublime package facilitates the npm install, simply run that command in the package's directory.

Follow the installation and Configuration for the plugin: https://github.com/ternjs/tern_for_sublime

Also, the "nuke_everything" option is not automatically reset to false in the .sublimious config, not sure if that makes a difference but it might be misleading

**Comment by dvcrn** [comment]
Released in [v0.6.0](https://github.com/dvcrn/sublimious/releases/tag/v0.6.0)
